version: '3.2'
services:
  rabbitmq_bootcamp:
    build:
      context: ./rabbitmq
      dockerfile: ./Dockerfile
    image: joaopemonteiro/rabbitmq_bootcamp:latest
    ports:
      - 15672:15672
      - 5672:5672
    container_name: rabbitmq_bootcamp_container
    networks:
      - backend
  postgres_bootcamp:
    build:
      context: ./postgres
      dockerfile: ./Dockerfile
    image: joaopemonteiro/postgres_bootcamp:latest
    ports:
      - 5432:5432
    container_name: postgres_bootcamp
    networks:
      - backend
  bootcamp-user-api:
    build:
      context: ../joao-pedro-monteiro-backend/app-user-api
      dockerfile: ../app-user-api/Dockerfile
    image: joaopemonteiro/app-user-api:latest
    ports:
      - 8080:8080
    container_name: app-user-api
    environment:
      - RABBIT_HOST=rabbitmq_bootcamp
      - POSTGRES_URL=postgres_bootcamp
      - POSTGRES_USER=bootcamp
      - POSTGRES_PASSWORD=bootcamppass
      - POSTGRES_DATABASE=bootcamp
    depends_on:
      - rabbitmq_bootcamp
      - postgres_bootcamp
    networks:
      - backend
  bootcamp-integration-api:
    build:
      context: ../joao-pedro-monteiro-backend/app-integration-api
      dockerfile: ../app-integration-api/Dockerfile
    image: joaopemonteiro/app-integration-api:latest
    ports:
      - 8082:8082
    container_name: app-integration-api
    environment:
      - RABBIT_HOST=rabbitmq_bootcamp
      - POSTGRES_URL=postgres_bootcamp
      - POSTGRES_USER=bootcamp
      - POSTGRES_PASSWORD=bootcamppass
      - POSTGRES_DATABASE=bootcamp
    depends_on:
      - rabbitmq_bootcamp
      - postgres_bootcamp
    networks:
      - backend
networks:
  backend:
    driver: "bridge"