create table album (
    value1 numeric(38,2) not null,
    id bigint generated by default as identity,
    id_user bigint,
    id_spotify varchar(100) not null,
    artist_name varchar(150) not null,
    image_url varchar(150) not null,
    name varchar(150) not null,
    primary key (id)
)