spring:
  application:
    name: Bootcamp Sysmap 2024 - Joao Pedro Monteiro
    main:
      allow-bean-definition-overriding: true
      allow-circular-references: true

server:
  port: 8080
  servlet:
    context-path: /api
